#!/bin/bash -e
# wod-up: Start up wordpress docker container and accompanying database.
#
# Usage:
#
#   wod up <name>

eval `wod bootstrap functions`

if [ $# -ne 1 ]; then
	print_help $0
	exit
fi

target="$1"
ensure_target $1

pushd `target_dir $target` >/dev/null
docker compose up -d && result=0 || result=$?

if [ $result ]; then
	SITEURL=`wp option get siteurl`
	echo "Website ready at ${SITEURL}"
fi
popd >/dev/null
exit $result
