#!/bin/bash -e
# wod-wp: Execute wp-cli command.
#
# Usage:
#
#   wod wp <name> <command> <options>
#
# name: name of the wod instance
#       If your working directory is inside the wod instance, then <name>
#       should not be specified.
#
# command: wp-cli command to run. For a list of commands, try 'wod wp <name> help'.
#

export SCRIPT_HOME=${SCRIPT_HOME:-/usr/lib/wod/bin}
. $SCRIPT_HOME/functions
wod_init

if [ `basename "$0"` == "wp" ]; then
    # Is current directory a descendent of WOD_HOME?
    if [[ $PWD == "${WOD_HOME}/"* ]]; then
        # Get the first path element after WOD_HOME
        instance=$(realpath --relative-to "${WOD_HOME}" `pwd` | cut -d'/' -f1)
    else # Call the system wp
        if [ $0 != `which wp` ]; then
            `which wp` "$@"
        else
            echo "wod wp does not function outside of wod environment."
            exit 1
        fi
    fi
else
    instance=$1
    shift
fi

container_name="${instance}_wordpress"
container=`docker container ls -q -f name="$container_name"`
if [ -z "$container" ]; then
    # Older versions of docker strip hyphens (between 2019-02 and 2021-02)
    container_name2="$(echo $container_name|tr -d '-')"
    container=`docker container ls -q -f name="$container_name2"`
fi
if [ -z "$container" ]; then
    echo "Error: Could not find container name '${container_name}'"
    if [ "$container_name" != "$container_name2" ]; then
        echo " or '${container_name2}'."
    fi
    exit 1
fi

# --user 33:33 is a workaround to run cli with the same UID/GID
# as www-data in the WordPress container. Problems arise because the
# containers have different UID/GID for www-data.
# See https://github.com/docker-library/wordpress/issues/256
#
# This trick should work in docker-compose.yml as well. Add  `user: "33:33"`.
# See https://github.com/docker/compose/issues/1532
#

# Use correct arguments depending on whether input is a tty or a pipe.
# https://stackoverflow.com/questions/911168/how-to-detect-if-my-shell-script-is-running-through-a-pipe
if [ -t 0 ] ; then
    inputargs=-it
else
    inputargs=-i
fi
docker run $inputargs --rm \
    --volumes-from $container \
    --network container:$container \
    --user 33:33 \
    wordpress:cli wp "$@"

