#!/bin/bash -e
# wod-ls: List containers created by wod.
#
# Usage:
#
#   wod ls
#
# The output shows in the following format:
#
#   dw <name>
#
# Where
#   'd' - '*' if database is running, '.' if not.
#   'w' - '*' if WordPress is running, '.' if not.
#   <name> - name of the containers.

export SCRIPT_HOME=${SCRIPT_HOME:-/usr/lib/wod/bin}
. $SCRIPT_HOME/functions
wod_init

if [ -n "$1" ]; then
	print_help $0
	exit
fi

instances=`ls ${WOD_HOME} --quoting-style=shell-escape`
if [ -z "${instances}" ]; then
    echo "No wod instances found."
    exit
fi

docker_is_running && docker=0 || docker=$?

# $1 = instance name
# $2 = db or wordpress
function print_container_status () {
    if [ $docker -ne 0 ]; then
        echo -n 'E '
    elif container_is_running "$1" "$2"; then
        echo -n '* '
    else
        echo -n '. '
    fi
}

echo "d w |"
echo "b p | name"
echo "====#========================="
for instance in ${instances}; do
    print_container_status "${instance}" db
    print_container_status "${instance}" wordpress
    echo "| $instance"
done
