#!/bin/bash -e
# wod-create: Create a new wordpress docker image in the working directory.
#
# Usage:
#
#   wod create <name> [backup-directory]

eval `wod bootstrap functions`

if [ -z "$1" ] || [ -n "$3" ]; then
	print_help $0
	exit
fi

# Set defaults
TEMPLATE_DIR=${TEMPLATE_DIR:-/usr/lib/wod/template}
TEMPLATE_NAME=${TEMPLATE_NAME:-no-mcrypt}
WORDPRESS_VERSION=${WORDPRESS_VERSION:-5.6.2}
PHP_VERSION=${PHP_VERSION:-7.3}
# NOTE: mcrypt does not exist in PHP 7.3; use 7.1 if you need it.
MYSQL_VERSION=${MYSQL_VERSION:-5.7}
SITEURL=${SITEURL:-"http://127.0.0.1:8000"}

# Example overrides.
# WORDPRESS_VERSION=4.9.6
# PHP_VERSION=7.1

# WORDPRESS_TAG=latest
# MYSQL_VERSION=5.7

# Override defaults with user configuration
if [ -f $HOME/.config/wod/wod.conf ]; then
    export $(grep -v '^#' $HOME/.config/wod/wod.conf | xargs -d '\n') &>/dev/null
fi

# Override configuration with command line arguments.
TARGET_NAME="$1"
TARGET_DIR=`target_dir "$TARGET_NAME"`
BACKUP_PREFIX=${2:-$BACKUP_PREFIX}

# Compute wordpress tag name
WORDPRESS_TAG=${WORDPRESS_TAG:-${WORDPRESS_VERSION}-php${PHP_VERSION}-apache}

# Prerequisites

# Ensure target name doesn't exist
if [ -e ${TARGET_DIR} ]; then
    echo "${TARGET_NAME} already exists."
    exit 1
fi

# $1 = name of container, "wordpress" or "db"
check_container() {
# Ensure container is not running
container_id=`docker container ls -qf "name=${TARGET_NAME}_$1_"`
if [ -n "${container_id}" ]; then
        echo "ERROR: Container ${TARGET_NAME}_$1_* already exists."
        echo "Run 'docker-compose -f ${TARGET_NAME}/docker-compose.yml down -v'."
        echo "If that doesn't work, try 'docker stop ${container_id}'."
        exit 1
fi
# Ensure container doesn't exist.
container_id=`docker container ls -aqf "name=${TARGET_NAME}_$1_"`
if [ -n "${container_id}" ]; then
        echo "ERROR: Container ${TARGET_NAME}_$1_* already exists."
        echo "Delete the container with 'docker rm -v ${container_id}'."
        exit 1
fi
}

check_container wordpress
check_container db

# Ensure db volume was deleted.
volume_name=`docker volume ls -qf "name=${TARGET_NAME}_db_data"`
if [ -n "${volume_name}" ]; then
        echo "ERROR: Volume ${volume_name} already exists."
        echo "Delete the volume with 'docker volume rm ${volume_name}'."
        exit 1
fi
# Ensure backup directory exists.
if [ -n "${BACKUP_PREFIX}" ] && [ ! -d "${BACKUP_PREFIX}" ]; then
    echo "Not a directory: ${BACKUP_PREFIX}."
    exit 1
fi


# Copy template to DOCKER_COMPOSE_DIR
echo "Creating container directory for '${TARGET_NAME}'"
mkdir -p ${TARGET_DIR}
cp -r ${TEMPLATE_DIR}/${TEMPLATE_NAME}/* ${TARGET_DIR}/

# Modify the tempate for the wordpress version, php version, mysql version.
sed -i -e "s/^FROM.*$/FROM wordpress:${WORDPRESS_TAG}/" \
    ${TARGET_DIR}/wp-php-custom/Dockerfile
# TODO: verify the wordpress tag is valid

wp_image_tag=wordpress:${WORDPRESS_VERSION}-php${PHP_VERSION}-custom
sed -i \
    -e "s/^\([[:space:]]*\)image: mysql.*$/\1image: mysql:${MYSQL_VERSION}/" \
    -e "s/^\([[:space:]]*\)image: wordpress.*$/\1image: ${wp_image_tag}/" \
    ${TARGET_DIR}/docker-compose.yml
# TODO: verify the mysql tag is valid

echo "Ready to run docker-compose up. Press Enter to continue"
read

pushd ${TARGET_DIR} >/dev/null
docker compose up -d
# The database needs a little time to come up.
sleep 10

# Install WordPress core. Autogenerate password.
wp core install --url=${SITEURL} --title="Testing WordPress" --admin_user="admin" --admin_email="admin@127.0.0.1"

if [ "${BACKUP_PREFIX}" != "" ]; then
    echo "Restore from backup."
    ${SCRIPT_HOME}/wod-restore $TARGET_NAME ${BACKUP_PREFIX}

    # Change the site url:
    wp option set siteurl ${SITEURL}
    wp option set home ${SITEURL}
fi

echo "Website ready at ${SITEURL}"
popd >/dev/null