#!/bin/bash -e
# wod-up: Take down wordpress docker container and accompanying database.
#
# Usage:
#
#   wod down <name>

export SCRIPT_HOME=${SCRIPT_HOME:-/usr/lib/wod/bin}
. $SCRIPT_HOME/functions
wod_init

if [ -z "$1" ] || [ -n "$2" ]; then
	print_help $0
	exit
fi

target="$1"
ensure_target $1

pushd `target_dir $target` >/dev/null
docker-compose down && result=0 || result=$?
popd >/dev/null
exit $result
