#!/bin/bash -e
# wod-rm: Delete wordpress docker image and accompanying database.
#
# Usage:
#
#   wod rm <name>

eval `wod bootstrap`
. $SCRIPT_HOME/functions

if [ $# -ne 1 ]; then
	print_help $0
	exit
fi

target="$1"
ensure_target $1
echo "Removing $target"
sudo -v

target_dir=`target_dir $target`
if [ -f "$target_dir"/docker-compose.yml ]; then
    ${SCRIPT_HOME}/wod-down $target
fi

if [ -d $target_dir ]; then
    sudo rm -rf "$target_dir"
fi

# Delete db volume
volume_name=`docker volume ls -qf "name=${target}_db_data"`
if [ -n "${volume_name}" ]; then
    docker volume rm "${volume_name}"
fi
