#!/bin/bash -e
# wod-ls: List containers created by wod.
#
# Usage:
#
#   wod ls
#
# The output shows in the following format:
#
#   dw <name>
#
# Where
#   'd' - '*' if database is running, '.' if not.
#   'w' - '*' if WordPress is running, '.' if not.
#   <name> - name of the containers.

eval `wod bootstrap functions`

if [ $# -ne 0 ]; then
	print_help $0
	exit
fi

instances=`ls ${WOD_HOME} --quoting-style=shell-escape`
if [ -z "${instances}" ]; then
    echo "No wod instances found."
    exit
fi

docker_is_running && docker=0 || docker=$?

# $1 = instance name
# $2 = db or wordpress
function print_container_status () {
    local status=1
    if [ $docker -ne 0 ]; then
        echo -n 'E '
    elif container_is_running "$1" "$2"; then
        echo -n '* '
        status=0
    else
        echo -n '. '
    fi
    return $status
}

echo "d w |"
echo "b p | name"
echo "====#========================="
for instance in ${instances}; do
    running=0
    print_container_status "${instance}" db || running=1
    print_container_status "${instance}" wordpress || running=1
    if [ $running -eq 0 ]; then
        pushd `target_dir $instance` >/dev/null
        echo "| $instance at $(wp option get siteurl)"
        popd >/dev/null
    else
        echo "| $instance"
    fi
done
